<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite parallel="classes" name="Failed suite [Suite]" guice-stage="DEVELOPMENT" verbose="0">
  <listeners>
    <listener class-name="rahulshettyacademy.TestComponents.Listeners"/>
  </listeners>
  <test thread-count="5" parallel="classes" name="Groceries App Test(failed)" verbose="0">
    <classes>
      <class name="rahulshettyacademy.groceries.app.GroceriesApp">
        <methods>
          <include name="beforeMethod"/>
          <include name="isProductOrdered"/>
          <include name="orderPlaced" invocation-numbers="0 1"/>
          <include name="afterMethod"/>
        </methods>
      </class> <!-- rahulshettyacademy.groceries.app.GroceriesApp -->
      <class name="rahulshettyacademy.groceries.app.ErrorValidations">
        <methods>
          <include name="beforeMethod"/>
          <include name="productAddedToCartValidation"/>
          <include name="afterMethod"/>
        </methods>
      </class> <!-- rahulshettyacademy.groceries.app.ErrorValidations -->
    </classes>
  </test> <!-- Groceries App Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
